import Header from '@/components/Header/Header';
import '../../styles/globals.css';
import Sidebar from '../../components/Sidebar/Sidebar';
import { groq } from 'next-sanity';
import { client } from '@/lib/sanity.client';

export const metadata = {
	title: 'Ezzy Blog',
	description: 'Generated by Next.js',
};
export const revalidate = 60;
const query = groq`
*[_type=='post']{
	...,
	author->,
	categories[]->,
} | order(_createdAt desc)
`;
export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// fetch data from studio
	const posts = await client.fetch(query);
	return (
		<html lang='en'>
			<body className='mx-auto'>
				<Header />
				<main className='grid grid-cols-9 w-full py-10 pb-20 mt-[200px]'>
					<section className='col-span-6 px-10'>
						<section>{children}</section>
					</section>
					<section className='col-span-3 px-10 border-l border-solid  border-gray-300'>
						<Sidebar posts={posts} />
					</section>
				</main>
			</body>
		</html>
	);
}
